import type { ZoneId } from "../types";
import { embeddedAudio, type EmbeddedAudio } from "./generated/audio.generated";
import {
  embeddedImpulses,
  type EmbeddedImpulse,
} from "./generated/impulses.generated";
import rawManifest from "./manifest.json";
import type { AudioCategory, AudioManifestEntry, ImpulseManifestEntry } from "./types";

interface AudioMetadata {
  readonly id: string;
  readonly category: AudioCategory;
  readonly fileName: string;
  readonly durationMs: number;
  readonly loop: boolean;
  readonly zone?: ZoneId;
  readonly pinId?: number;
  readonly purpose: string;
}

interface ImpulseMetadata {
  readonly id: string;
  readonly zone: ZoneId;
  readonly fileName: string;
  readonly durationMs: number;
  readonly preDelayMs: number;
  readonly wet: number;
  readonly seed: number;
  readonly filterCoefficient: number;
  readonly decayPower: number;
  readonly purpose: string;
}

export interface AudioAssetRecord extends AudioManifestEntry, EmbeddedAudio {
  readonly fileName: string;
  readonly durationMs: number;
  readonly durationSeconds: number;
  readonly purpose: string;
}

export interface ImpulseAssetRecord extends ImpulseManifestEntry, EmbeddedImpulse {
  readonly fileName: string;
  readonly durationMs: number;
  readonly durationSeconds: number;
  /** Leading digital silence already baked into the impulse WAV. */
  readonly preDelayMs: number;
  readonly seed: number;
  readonly filterCoefficient: number;
  readonly decayPower: number;
  readonly purpose: string;
}

const metadata = rawManifest as unknown as {
  readonly audio: readonly AudioMetadata[];
  readonly impulses: readonly ImpulseMetadata[];
};

function required<T>(value: T | undefined, id: string): T {
  if (value === undefined) throw new Error(`Missing generated bytes for audio asset ${id}`);
  return value;
}

export const audioManifest: readonly AudioAssetRecord[] = metadata.audio.map(
  (entry) => ({
    ...entry,
    ...required(embeddedAudio[entry.id], entry.id),
    durationSeconds: entry.durationMs / 1000,
    mimeType: "audio/wav" as const,
  }),
);

export const impulseManifest: readonly ImpulseAssetRecord[] = metadata.impulses.map(
  (entry) => ({
    ...entry,
    ...required(embeddedImpulses[entry.id], entry.id),
    durationSeconds: entry.durationMs / 1000,
    mimeType: "audio/wav" as const,
  }),
);

/** Detailed aliases for build tooling and curator checks. */
export const audioAssets = audioManifest;
export const impulseAssets = impulseManifest;
